apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tod.fullname" . }}-firmware-cache
  labels:
    {{- include "tod.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.firmwareCache.storageClass }}
  storageClassName: {{ .Values.storage.firmwareCache.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.firmwareCache.size }}
