"""scripts/upgrade_env.py adds newly required variables to an existing env file.

Existing installs upgrading past a release that introduces a required
variable should not have to hand-edit .env.prod; the script appends what is
missing with a generated value and touches nothing else.
"""

import importlib.util
import pathlib

SCRIPT = pathlib.Path(__file__).resolve().parents[2] / "scripts" / "upgrade_env.py"


def _load():
    spec = importlib.util.spec_from_file_location("upgrade_env", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_adds_missing_required_keys_and_keeps_everything_else(tmp_path):
    env = tmp_path / ".env.prod"
    env.write_text("# generated by setup.py\nJWT_SECRET_KEY=abc\nSMTP_HOST=\n")
    mod = _load()

    added = mod.upgrade_env_file(env)

    assert added == ["WINBOX_WORKER_TOKEN"]
    text = env.read_text()
    assert text.startswith("# generated by setup.py\nJWT_SECRET_KEY=abc\nSMTP_HOST=\n")
    values = dict(
        line.split("=", 1) for line in text.splitlines() if "=" in line and not line.startswith("#")
    )
    assert len(values["WINBOX_WORKER_TOKEN"]) >= 32
    backups = list(tmp_path.glob(".env.prod.backup.*"))
    assert (
        len(backups) == 1
        and backups[0].read_text() == "# generated by setup.py\nJWT_SECRET_KEY=abc\nSMTP_HOST=\n"
    )
    # The backup holds the same secrets as the env file: owner-only, whatever the umask.
    assert backups[0].stat().st_mode & 0o777 == 0o600


def test_is_idempotent_and_never_overwrites(tmp_path):
    env = tmp_path / ".env.prod"
    env.write_text("WINBOX_WORKER_TOKEN=keep-me\n")
    mod = _load()

    assert mod.upgrade_env_file(env) == []
    assert env.read_text() == "WINBOX_WORKER_TOKEN=keep-me\n"
    assert list(tmp_path.glob(".env.prod.backup.*")) == []


def test_empty_value_counts_as_missing(tmp_path):
    env = tmp_path / ".env.prod"
    env.write_text("WINBOX_WORKER_TOKEN=\n")
    mod = _load()

    assert mod.upgrade_env_file(env) == ["WINBOX_WORKER_TOKEN"]
    values = dict(line.split("=", 1) for line in env.read_text().splitlines() if "=" in line)
    assert values["WINBOX_WORKER_TOKEN"]


def test_dotenv_quoting_and_inline_comments(tmp_path):
    """Compose treats `KEY="" # later` as empty; so must the script, or it tells
    the operator to re-run something that does nothing."""
    env = tmp_path / ".env.prod"
    env.write_text('WINBOX_WORKER_TOKEN="" # set later\nJWT_SECRET_KEY=abc # keep\n')
    mod = _load()

    assert mod.upgrade_env_file(env) == ["WINBOX_WORKER_TOKEN"]
    assert mod._present_values("A='x' # c\nB=\"y z\"\nC=plain # c\nD=''\n") == {
        "A": "x",
        "B": "y z",
        "C": "plain",
        "D": "",
    }


def test_missing_file_is_an_error(tmp_path):
    mod = _load()
    try:
        mod.upgrade_env_file(tmp_path / "nope.env")
    except FileNotFoundError:
        return
    raise AssertionError("a missing env file must not be silently created")
