/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVpnRouteImport } from './routes/_authenticated/vpn'
import { Route as AuthenticatedTransparencyRouteImport } from './routes/_authenticated/transparency'
import { Route as AuthenticatedTopologyRouteImport } from './routes/_authenticated/topology'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedFirmwareRouteImport } from './routes/_authenticated/firmware'
import { Route as AuthenticatedConfigEditorRouteImport } from './routes/_authenticated/config-editor'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedBulkCommandsRouteImport } from './routes/_authenticated/bulk-commands'
import { Route as AuthenticatedBatchConfigRouteImport } from './routes/_authenticated/batch-config'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAlertRulesRouteImport } from './routes/_authenticated/alert-rules'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants/index'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings.api-keys'
import { Route as AuthenticatedTenantsTenantIdIndexRouteImport } from './routes/_authenticated/tenants/$tenantId/index'
import { Route as AuthenticatedTenantsTenantIdUsersRouteImport } from './routes/_authenticated/tenants/$tenantId/users'
import { Route as AuthenticatedTenantsTenantIdDevicesIndexRouteImport } from './routes/_authenticated/tenants/$tenantId/devices/index'
import { Route as AuthenticatedTenantsTenantIdDevicesScanRouteImport } from './routes/_authenticated/tenants/$tenantId/devices/scan'
import { Route as AuthenticatedTenantsTenantIdDevicesAdoptRouteImport } from './routes/_authenticated/tenants/$tenantId/devices/adopt'
import { Route as AuthenticatedTenantsTenantIdDevicesAddRouteImport } from './routes/_authenticated/tenants/$tenantId/devices/add'
import { Route as AuthenticatedTenantsTenantIdDevicesDeviceIdRouteImport } from './routes/_authenticated/tenants/$tenantId/devices/$deviceId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVpnRoute = AuthenticatedVpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransparencyRoute =
  AuthenticatedTransparencyRouteImport.update({
    id: '/transparency',
    path: '/transparency',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTopologyRoute = AuthenticatedTopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFirmwareRoute = AuthenticatedFirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigEditorRoute =
  AuthenticatedConfigEditorRouteImport.update({
    id: '/config-editor',
    path: '/config-editor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBulkCommandsRoute =
  AuthenticatedBulkCommandsRouteImport.update({
    id: '/bulk-commands',
    path: '/bulk-commands',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBatchConfigRoute =
  AuthenticatedBatchConfigRouteImport.update({
    id: '/batch-config',
    path: '/batch-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertRulesRoute = AuthenticatedAlertRulesRouteImport.update({
  id: '/alert-rules',
  path: '/alert-rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedTenantsTenantIdIndexRoute =
  AuthenticatedTenantsTenantIdIndexRouteImport.update({
    id: '/tenants/$tenantId/',
    path: '/tenants/$tenantId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdUsersRoute =
  AuthenticatedTenantsTenantIdUsersRouteImport.update({
    id: '/tenants/$tenantId/users',
    path: '/tenants/$tenantId/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdDevicesIndexRoute =
  AuthenticatedTenantsTenantIdDevicesIndexRouteImport.update({
    id: '/tenants/$tenantId/devices/',
    path: '/tenants/$tenantId/devices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdDevicesScanRoute =
  AuthenticatedTenantsTenantIdDevicesScanRouteImport.update({
    id: '/tenants/$tenantId/devices/scan',
    path: '/tenants/$tenantId/devices/scan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdDevicesAdoptRoute =
  AuthenticatedTenantsTenantIdDevicesAdoptRouteImport.update({
    id: '/tenants/$tenantId/devices/adopt',
    path: '/tenants/$tenantId/devices/adopt',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdDevicesAddRoute =
  AuthenticatedTenantsTenantIdDevicesAddRouteImport.update({
    id: '/tenants/$tenantId/devices/add',
    path: '/tenants/$tenantId/devices/add',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdDevicesDeviceIdRoute =
  AuthenticatedTenantsTenantIdDevicesDeviceIdRouteImport.update({
    id: '/tenants/$tenantId/devices/$deviceId',
    path: '/tenants/$tenantId/devices/$deviceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/about': typeof AuthenticatedAboutRoute
  '/alert-rules': typeof AuthenticatedAlertRulesRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/batch-config': typeof AuthenticatedBatchConfigRoute
  '/bulk-commands': typeof AuthenticatedBulkCommandsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/config-editor': typeof AuthenticatedConfigEditorRoute
  '/firmware': typeof AuthenticatedFirmwareRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/map': typeof AuthenticatedMapRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/setup': typeof AuthenticatedSetupRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/topology': typeof AuthenticatedTopologyRoute
  '/transparency': typeof AuthenticatedTransparencyRoute
  '/vpn': typeof AuthenticatedVpnRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersRoute
  '/tenants/$tenantId/': typeof AuthenticatedTenantsTenantIdIndexRoute
  '/tenants/$tenantId/devices/$deviceId': typeof AuthenticatedTenantsTenantIdDevicesDeviceIdRoute
  '/tenants/$tenantId/devices/add': typeof AuthenticatedTenantsTenantIdDevicesAddRoute
  '/tenants/$tenantId/devices/adopt': typeof AuthenticatedTenantsTenantIdDevicesAdoptRoute
  '/tenants/$tenantId/devices/scan': typeof AuthenticatedTenantsTenantIdDevicesScanRoute
  '/tenants/$tenantId/devices/': typeof AuthenticatedTenantsTenantIdDevicesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/about': typeof AuthenticatedAboutRoute
  '/alert-rules': typeof AuthenticatedAlertRulesRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/batch-config': typeof AuthenticatedBatchConfigRoute
  '/bulk-commands': typeof AuthenticatedBulkCommandsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/config-editor': typeof AuthenticatedConfigEditorRoute
  '/firmware': typeof AuthenticatedFirmwareRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/map': typeof AuthenticatedMapRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/setup': typeof AuthenticatedSetupRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/topology': typeof AuthenticatedTopologyRoute
  '/transparency': typeof AuthenticatedTransparencyRoute
  '/vpn': typeof AuthenticatedVpnRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
  '/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdIndexRoute
  '/tenants/$tenantId/devices/$deviceId': typeof AuthenticatedTenantsTenantIdDevicesDeviceIdRoute
  '/tenants/$tenantId/devices/add': typeof AuthenticatedTenantsTenantIdDevicesAddRoute
  '/tenants/$tenantId/devices/adopt': typeof AuthenticatedTenantsTenantIdDevicesAdoptRoute
  '/tenants/$tenantId/devices/scan': typeof AuthenticatedTenantsTenantIdDevicesScanRoute
  '/tenants/$tenantId/devices': typeof AuthenticatedTenantsTenantIdDevicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/alert-rules': typeof AuthenticatedAlertRulesRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/batch-config': typeof AuthenticatedBatchConfigRoute
  '/_authenticated/bulk-commands': typeof AuthenticatedBulkCommandsRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/config-editor': typeof AuthenticatedConfigEditorRoute
  '/_authenticated/firmware': typeof AuthenticatedFirmwareRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/topology': typeof AuthenticatedTopologyRoute
  '/_authenticated/transparency': typeof AuthenticatedTransparencyRoute
  '/_authenticated/vpn': typeof AuthenticatedVpnRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/_authenticated/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersRoute
  '/_authenticated/tenants/$tenantId/': typeof AuthenticatedTenantsTenantIdIndexRoute
  '/_authenticated/tenants/$tenantId/devices/$deviceId': typeof AuthenticatedTenantsTenantIdDevicesDeviceIdRoute
  '/_authenticated/tenants/$tenantId/devices/add': typeof AuthenticatedTenantsTenantIdDevicesAddRoute
  '/_authenticated/tenants/$tenantId/devices/adopt': typeof AuthenticatedTenantsTenantIdDevicesAdoptRoute
  '/_authenticated/tenants/$tenantId/devices/scan': typeof AuthenticatedTenantsTenantIdDevicesScanRoute
  '/_authenticated/tenants/$tenantId/devices/': typeof AuthenticatedTenantsTenantIdDevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/about'
    | '/alert-rules'
    | '/alerts'
    | '/audit'
    | '/batch-config'
    | '/bulk-commands'
    | '/certificates'
    | '/config-editor'
    | '/firmware'
    | '/maintenance'
    | '/map'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/templates'
    | '/topology'
    | '/transparency'
    | '/vpn'
    | '/settings/api-keys'
    | '/tenants/'
    | '/tenants/$tenantId/users'
    | '/tenants/$tenantId/'
    | '/tenants/$tenantId/devices/$deviceId'
    | '/tenants/$tenantId/devices/add'
    | '/tenants/$tenantId/devices/adopt'
    | '/tenants/$tenantId/devices/scan'
    | '/tenants/$tenantId/devices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/about'
    | '/alert-rules'
    | '/alerts'
    | '/audit'
    | '/batch-config'
    | '/bulk-commands'
    | '/certificates'
    | '/config-editor'
    | '/firmware'
    | '/maintenance'
    | '/map'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/templates'
    | '/topology'
    | '/transparency'
    | '/vpn'
    | '/'
    | '/settings/api-keys'
    | '/tenants'
    | '/tenants/$tenantId/users'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/devices/$deviceId'
    | '/tenants/$tenantId/devices/add'
    | '/tenants/$tenantId/devices/adopt'
    | '/tenants/$tenantId/devices/scan'
    | '/tenants/$tenantId/devices'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/about'
    | '/_authenticated/alert-rules'
    | '/_authenticated/alerts'
    | '/_authenticated/audit'
    | '/_authenticated/batch-config'
    | '/_authenticated/bulk-commands'
    | '/_authenticated/certificates'
    | '/_authenticated/config-editor'
    | '/_authenticated/firmware'
    | '/_authenticated/maintenance'
    | '/_authenticated/map'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/_authenticated/templates'
    | '/_authenticated/topology'
    | '/_authenticated/transparency'
    | '/_authenticated/vpn'
    | '/_authenticated/'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/tenants/'
    | '/_authenticated/tenants/$tenantId/users'
    | '/_authenticated/tenants/$tenantId/'
    | '/_authenticated/tenants/$tenantId/devices/$deviceId'
    | '/_authenticated/tenants/$tenantId/devices/add'
    | '/_authenticated/tenants/$tenantId/devices/adopt'
    | '/_authenticated/tenants/$tenantId/devices/scan'
    | '/_authenticated/tenants/$tenantId/devices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vpn': {
      id: '/_authenticated/vpn'
      path: '/vpn'
      fullPath: '/vpn'
      preLoaderRoute: typeof AuthenticatedVpnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transparency': {
      id: '/_authenticated/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof AuthenticatedTransparencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topology': {
      id: '/_authenticated/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof AuthenticatedTopologyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firmware': {
      id: '/_authenticated/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof AuthenticatedFirmwareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config-editor': {
      id: '/_authenticated/config-editor'
      path: '/config-editor'
      fullPath: '/config-editor'
      preLoaderRoute: typeof AuthenticatedConfigEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bulk-commands': {
      id: '/_authenticated/bulk-commands'
      path: '/bulk-commands'
      fullPath: '/bulk-commands'
      preLoaderRoute: typeof AuthenticatedBulkCommandsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/batch-config': {
      id: '/_authenticated/batch-config'
      path: '/batch-config'
      fullPath: '/batch-config'
      preLoaderRoute: typeof AuthenticatedBatchConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alert-rules': {
      id: '/_authenticated/alert-rules'
      path: '/alert-rules'
      fullPath: '/alert-rules'
      preLoaderRoute: typeof AuthenticatedAlertRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/tenants/$tenantId/': {
      id: '/_authenticated/tenants/$tenantId/'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/users': {
      id: '/_authenticated/tenants/$tenantId/users'
      path: '/tenants/$tenantId/users'
      fullPath: '/tenants/$tenantId/users'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/devices/': {
      id: '/_authenticated/tenants/$tenantId/devices/'
      path: '/tenants/$tenantId/devices'
      fullPath: '/tenants/$tenantId/devices/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/devices/scan': {
      id: '/_authenticated/tenants/$tenantId/devices/scan'
      path: '/tenants/$tenantId/devices/scan'
      fullPath: '/tenants/$tenantId/devices/scan'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdDevicesScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/devices/adopt': {
      id: '/_authenticated/tenants/$tenantId/devices/adopt'
      path: '/tenants/$tenantId/devices/adopt'
      fullPath: '/tenants/$tenantId/devices/adopt'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdDevicesAdoptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/devices/add': {
      id: '/_authenticated/tenants/$tenantId/devices/add'
      path: '/tenants/$tenantId/devices/add'
      fullPath: '/tenants/$tenantId/devices/add'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdDevicesAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/devices/$deviceId': {
      id: '/_authenticated/tenants/$tenantId/devices/$deviceId'
      path: '/tenants/$tenantId/devices/$deviceId'
      fullPath: '/tenants/$tenantId/devices/$deviceId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdDevicesDeviceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAlertRulesRoute: typeof AuthenticatedAlertRulesRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBatchConfigRoute: typeof AuthenticatedBatchConfigRoute
  AuthenticatedBulkCommandsRoute: typeof AuthenticatedBulkCommandsRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedConfigEditorRoute: typeof AuthenticatedConfigEditorRoute
  AuthenticatedFirmwareRoute: typeof AuthenticatedFirmwareRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTopologyRoute: typeof AuthenticatedTopologyRoute
  AuthenticatedTransparencyRoute: typeof AuthenticatedTransparencyRoute
  AuthenticatedVpnRoute: typeof AuthenticatedVpnRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
  AuthenticatedTenantsTenantIdUsersRoute: typeof AuthenticatedTenantsTenantIdUsersRoute
  AuthenticatedTenantsTenantIdIndexRoute: typeof AuthenticatedTenantsTenantIdIndexRoute
  AuthenticatedTenantsTenantIdDevicesDeviceIdRoute: typeof AuthenticatedTenantsTenantIdDevicesDeviceIdRoute
  AuthenticatedTenantsTenantIdDevicesAddRoute: typeof AuthenticatedTenantsTenantIdDevicesAddRoute
  AuthenticatedTenantsTenantIdDevicesAdoptRoute: typeof AuthenticatedTenantsTenantIdDevicesAdoptRoute
  AuthenticatedTenantsTenantIdDevicesScanRoute: typeof AuthenticatedTenantsTenantIdDevicesScanRoute
  AuthenticatedTenantsTenantIdDevicesIndexRoute: typeof AuthenticatedTenantsTenantIdDevicesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAlertRulesRoute: AuthenticatedAlertRulesRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBatchConfigRoute: AuthenticatedBatchConfigRoute,
  AuthenticatedBulkCommandsRoute: AuthenticatedBulkCommandsRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedConfigEditorRoute: AuthenticatedConfigEditorRoute,
  AuthenticatedFirmwareRoute: AuthenticatedFirmwareRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTopologyRoute: AuthenticatedTopologyRoute,
  AuthenticatedTransparencyRoute: AuthenticatedTransparencyRoute,
  AuthenticatedVpnRoute: AuthenticatedVpnRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
  AuthenticatedTenantsTenantIdUsersRoute:
    AuthenticatedTenantsTenantIdUsersRoute,
  AuthenticatedTenantsTenantIdIndexRoute:
    AuthenticatedTenantsTenantIdIndexRoute,
  AuthenticatedTenantsTenantIdDevicesDeviceIdRoute:
    AuthenticatedTenantsTenantIdDevicesDeviceIdRoute,
  AuthenticatedTenantsTenantIdDevicesAddRoute:
    AuthenticatedTenantsTenantIdDevicesAddRoute,
  AuthenticatedTenantsTenantIdDevicesAdoptRoute:
    AuthenticatedTenantsTenantIdDevicesAdoptRoute,
  AuthenticatedTenantsTenantIdDevicesScanRoute:
    AuthenticatedTenantsTenantIdDevicesScanRoute,
  AuthenticatedTenantsTenantIdDevicesIndexRoute:
    AuthenticatedTenantsTenantIdDevicesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
